Added calculations.c
audio-engineer/aau-p1-software pull request #18
Opened 2023-11-30 13:24 UTC by Danar435

2023-12-02 17:43 UTC, TexWO approved these changes

2023-12-02 21:24 UTC, audio-engineer requested changes

2023-12-02 21:24 UTC, audio-engineer commented on tests/calculations.cc
@Danar435 Please split the tests into multiple tests, not to have more than one expectation per test. Just reuse the TEST macro for all of your test cases and give them unique names (second parameter) in the same test suite (first parameter). Let me know if you need help

2023-12-02 23:47 UTC, Danar435 commented on tests/calculations.cc
This would've been tedious but thank god for copilot

2023-12-03 12:12 UTC, audio-engineer approved these changes

2023-12-03 12:19 UTC, merged