change the structure of ...
audio-engineer/aau-p1-software pull request #22
Opened 2023-12-02 20:18 UTC by SebastianMygind

InitializePreferenceFile and SetUserPreference So one function does not call the other, and fix possible memory leak.
I think this makes it more clear where the file is initialized if it does not already exists.

2023-12-02 21:17 UTC, audio-engineer commented
@SebastianMygind Where do you potential memory leaks? Can you explain your code and rationale? It doesn't make a lot of sense to me. E.g. why would we want to expose `InitializePreferenceFile` as part of the API, when it's supposed to be an implementation detail? Where does the file size of `10` come from?

2023-12-02 23:33 UTC, Danar435 approved these changes

2023-12-03 13:22 UTC, MadsHeilmann approved these changes

2023-12-04 19:33 UTC, audio-engineer requested changes

2023-12-04 19:33 UTC, audio-engineer commented on src/preferences.c
> +  cJSON_Delete(kJsonPreferences);
@SebastianMygind Ok, I see now what you refer to as a "memory leak". Good addition 👍

2023-12-04 19:33 UTC, audio-engineer commented on src/preferences.c
@SebastianMygind I like the usage of `cJSON_Delete` but I am not a fan of the other changes. While the idea is good, it doesn't take into account the already existing behavior of e.g. `fopen`.
See https://en.cppreference.com/w/c/io/fopen. If you attempt to open a non-existent location in the filesystem in `w` mode, `fopen` will create a new file at the given location, rendering your "file size is less than some arbitrary file size" logic redundant.

2023-12-04 19:33 UTC, audio-engineer commented on src/preferences.h
@SebastianMygind Also, I don't think we should expose `InitializePreferenceFile` since it should be called once at maximum during the software's runtime, and is therefore not _just_ some reusable function. If you want to make sure that `preferences.json` exists when either `SetUserPreference` or `GetUserPreference` is called, it should be solved in another way, i.e. with logic checks.

2023-12-06 11:57 UTC, audio-engineer approved these changes

2023-12-06 11:58 UTC, TexWO approved these changes

2023-12-06 11:58 UTC, merged