add sorting function
audio-engineer/aau-p1-software pull request #29
Opened 2023-12-11 13:38 UTC by SebastianMygind

It works but the code is not pretty...

2023-12-11 14:10 UTC, audio-engineer requested changes

2023-12-11 14:10 UTC, audio-engineer commented on src/evaluate.c
> +int RouteCompareOverall(const void* ptr1, const void* ptr2);
@SebastianMygind
![ce0133aa153efc547b532fd26d558408](https://github.com/audio-engineer/aau-p1-software/assets/70742985/a7a26a26-ca41-4247-a32a-b307f3e2927c)

2023-12-11 14:12 UTC, audio-engineer commented
@SebastianMygind The code is a bit messy and ClangFormat is failing. Remove those unnecessary function signatures and and format the code properly - then it can be merged.
I will try to refactor it together with the other code later this week to bind everything together.

2023-12-13 11:15 UTC, audio-engineer approved these changes

2023-12-13 11:41 UTC, MadsHeilmann approved these changes

2023-12-13 11:41 UTC, merged